### ISSUE TITLE
Adding License Information + Other Metadata 

### ISSUE THREAD

**Issue by deemp** [nix-community/nix-vscode-extensions#1]
Start of the discussion: https://github.com/orgs/nix-community/teams/nix-vscode-extensions

- `nvfetcher` may produce incorrect `.nix ` files because it uses simple string manipulation
  - [x] Ex: invalid `description` attribute
     - [x] Solution: no `description` attribute
- `nvfetcher` doesn't extract metadata from the Microsoft marketplace extensions.
  - [ ]  Decide if we need such metadata
  - [ ] If yes, try to fix (see https://github.com/NixOS/nixpkgs/pull/161369)
    - [ ] We can extract the metadata from the manifest `package.json` inside the `.vsix` file.
    - [ ] The file can be extracted with unzip without decompressing the whole extension.

**Comment by AmeerTaweel** [comment]
To answer this:

> Can you give an example of such a broken `.nix` file?

I found an example in the history of the repo:
https://github.com/nix-community/nix-vscode-extensions/commit/a77f1d354a4d18d1cc3e1d3ac98bb1684a5aacc0

I fixed an issue with a file that was auto-generated. So `nvfetcher` indeed can produce problematic files.

**Comment by deemp** [comment]
Now, the generated files don't have a `description` attribute.

**Comment by AmeerTaweel** [comment]
I stopped getting metadata via `nvfetcher` because it would break every time the action runs. And I didn't want to keep fixing the broken stuff manually.

**Comment by AmeerTaweel** [comment]
I didn't have time to work on this for a while, and I can see a lot has happened. Thanks for your great work @deemp!

I checked `data/cache` and it seems that the current fetcher also does not fetch license info.

I proposed adding license info because some users might not want to use unfree extensions. What do you think? Should we dismiss the proposal or should I work on it?

**Comment by deemp** [comment]
Hi, @AmeerTaweel! 

We neither fetch nor record license info. This info may bloat the flake. I suggest we don't implement this feature until someone asks about it. When it is the case, we can make another list of extensions in the configuration and fetch license info just for them.

**Comment by AmeerTaweel** [comment]
Okay. I guess I will close this for now. If someone wants this they can open a new issue.
