### ISSUE TITLE
Error 404 - regression from #21

### ISSUE THREAD

**Issue by tennox** [nix-community/nix-vscode-extensions#22]
I'm on revision `fd916a94f287d9e1762f02df4f5984867c770b9f` and I'm getting this error (cleaned up):

```
error: builder for '/nix/store/gxid8alyj5bkjdg3aniv0b44m9c2kq3x-shellcheck-0.32.5.zip.drv' failed with exit code 1;
       > trying https://open-vsx.org/api/timonwong/shellcheck/0.32.5/file/timonwong.shellcheck-0.32.5@linux-x64.vsix
       > curl: (22) The requested URL returned error: 404
       > error: cannot download shellcheck-0.32.5.zip from any mirror
```

I've checked in devtools on [open-vsx](https://open-vsx.org/extension/timonwong/shellcheck), and the url used there seems to be only slightly different (and works):
`https://open-vsx.org/api/timonwong/shellcheck/linux-x64/0.32.5/file/timonwong.shellcheck-0.32.5@linux-x64.vsix`

The only difference is the `linux-x64/` before the version in the path.

### Workaround
back to the revision I was on before:
```nix
{
  inputs.nix-vscode-extensions.url = "github:nix-community/nix-vscode-extensions/fd916a94f287d9e1762f02df4f5984867c770b9f";
}
```

```nix
{extensions = with inputs.nix-vscode-extensions.extensions.${pkgs.system}; (
    with open-vsx; [
      timonwong.shellcheck
    ]
);}
```

**Comment by deemp** [comment]
@tennox, is it OK now?

**Comment by tennox** [comment]
> @tennox, is it OK now?

@deemp Yes, confirmed working on latest (10ce968c6896fb0866d4c80c7e4c684f849d56d2) - thank you :heart:
