### ISSUE TITLE
Github copilot missing

### ISSUE THREAD

**Issue by deontologician** [nix-community/nix-vscode-extensions#28]
For some reason, `github.copilot` doesn't exist in vscode-marketplace, (though for some reason github.copilot-labs does exist). Is there any kind of filter happening in the job that pulls extensions?

**Comment by deemp** [comment]
Hi, @deontologician! Indeed, a flag was missing. Fixed by https://github.com/nix-community/nix-vscode-extensions/commit/52c41ecabfa6019fdb9a348bc5cd45a8e4cbb5d6.

There's now `copilot-nightly`.

```console
nix-repl> :lf github:nix-community/nix-vscode-extensions/6bbe040dccef65112d52306286ae3b7fe3320765
nix-repl> extensions.x86_64-linux.vscode-marketplace.github.copilot-nightly
«derivation /nix/store/sckrg9a317yx007c2aarwv5mm4nsls1p-vscode-extension-github-copilot-nightly-1.94.226.drv»
```
