### ISSUE TITLE
Improve documentation?

### ISSUE THREAD

**Issue by DrymarchonShaun** [nix-community/nix-vscode-extensions#29]
I'm trying to figure out how I would go about integrating this into my home-manager configuration and the documentation/examples given in the readme doesn't seem to explain it. 

Ideally I'd like to be able to use this with `programs.vscode.extensions` in home-manager,  (I do have `programs.vscode.package` set to `pkgs.vscodium`).

**Comment by deemp** [comment]
@AmeerTaweel, I have no experience with home-manager. Do you?

**Comment by DrymarchonShaun** [comment]
I think I figured it out. I wasn't familar with how overlays work, and the readme doesn't elaborate on where you add it. 

_Not in anyway nicely formatted to actually be put into documentation, but what I had do to was:_

add the input to `flake.nix` - This is covered
```
  inputs = {
  # ...
    # VSCodium Extensions
    nix-vscode-extensions.url = "github:nix-community/nix-vscode-extensions";
  };
```
Then in my home-manager config (_location is very user dependent_) I added the overlay to nixpkgs - ( I think is how the overlay is used in a regular configuration as well, this is the main part that confused me and I don't think is covered.)

```
nixpkgs = {
     overlays = [
      # ...

      inputs.nix-vscode-extensions.overlays.default
    ];
    config = {
       # ...
    };
  };
```

And then I was able to just add `vscode-marketplace` onto `with pkgs;` 

```

 programs.vscode = {
    enable = true;
    package = pkgs.vscodium;
      extensions = with pkgs.vscode-marketplace; [
    # Make sure these are lowercase! 
           pinage404.nix-extension-pack
           # ...
      ];
  };
  ```

**Comment by deemp** [comment]
@DrymarchonShaun , I added an [Overlay](https://github.com/nix-community/nix-vscode-extensions#overlay) section to the `README`. Is it more straightforward now?

**Comment by DrymarchonShaun** [comment]
yeah, thats fine.
