### ISSUE TITLE
Is it possible to use this with `home-manager` without using flakes?

### ISSUE THREAD

**Issue by hyperspace01** [nix-community/nix-vscode-extensions#30]
#29 mentions home-manager, however only when using flakes. I currently have no interest in using flakes, so I hope it's possible to use it with a traditional config.
Thanks :smile:

**Comment by DrymarchonShaun** [comment]
I don't have a nixos system available at the moment but I think [this](https://github.com/nix-community/nix-vscode-extensions#without-flakes) might be what you are looking for?

**Comment by hyperspace01** [comment]
Does that indeed apply to home-manager? I'm not very knowledgeable on the Nix language so I have no idea how to translate that to something else

**Comment by deemp** [comment]
Hi, @hyperspace01! 

I don't use home manager. I suggest you first explore the `extensions` attrset in repl.

```nix
nix-repl> t = (import (builtins.fetchGit {
            url = "https://github.com/nix-community/nix-vscode-extensions";
            ref = "refs/heads/master";
            rev = "c43d9089df96cf8aca157762ed0e2ddca9fcd71e";
          })).extensions

nix-repl> t.x86_64-linux.<TAB>
t.x86_64-linux.forVSCodeVersion            t.x86_64-linux.open-vsx-release            t.x86_64-linux.vscode-marketplace-release
t.x86_64-linux.open-vsx                    t.x86_64-linux.vscode-marketplace
```

If you use `overlays.default` on nixpkgs, you should have a `pkgs.vscode-extensions` and other attrsets.

```console
nix-repl> pkgs = import <nixpkgs> {system = builtins.currentSystem; overlays = [overlays.default];}
nix-repl> pkgs.vscod<TAB>
pkgs.vscode                        pkgs.vscode-langservers-extracted  pkgs.vscode-with-extensions
pkgs.vscode-extensions             pkgs.vscode-marketplace            pkgs.vscodium
pkgs.vscode-fhs                    pkgs.vscode-marketplace-release    pkgs.vscodium-fhs
pkgs.vscode-fhsWithPackages        pkgs.vscode-utils                  pkgs.vscodium-fhsWithPackages
```

Choose the necessary attrset and use like `with pkgs.vscode-marketplace;`

**Comment by jacekszymanski** [comment]
You forgot `;` at the end of line 152.

But I'd try something like:

```
extensions = 
  with (import (builtins.fetchGit {
        url = "https://github.com/nix-community/nix-vscode-extensions";
        ref = "refs/heads/master";
        rev = "c43d9089df96cf8aca157762ed0e2ddca9fcd71e";
  })).extensions.x86_64-linux; [
  vscodevim.vim
 ];
```

**Comment by deemp** [comment]
@hyperspace01 , you'll be more productive if you study the Nix language basics
https://nixos.org/manual/nix/stable/language/constructs.html#language-constructs

**Comment by hyperspace01** [comment]
Alright, thanks a lot everyone!
