### ISSUE TITLE
build codelldb from github

### ISSUE THREAD

**Issue by cathaysia** [nix-community/nix-vscode-extensions#34]
the [codelldb](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) in marketplace is just a downloader, it download the truely plugin from [github](https://github.com/vadimcn/codelldb/releases/tag/v1.9.2) .

if it's possible replace codelldb with the github ones?

I build codelldb by this codes:

```nix
  vscode-lldb = pkgs.vscode-utils.buildVscodeExtension {
    name = "vadimcn.vscode-lldb";
    vscodeExtPublisher = "vadimcn";
    vscodeExtName = "codelldb";
    src = (pkgs.fetchurl {
      url = "https://github.com/vadimcn/codelldb/releases/download/v1.9.2/codelldb-x86_64-linux.vsix";
      sha256 = "sha256-iYvSKyUFsSZx/ufS/hq7OE3GDRP1/sK0tlDQ2sP4PXU=";
      name = "codelldb.zip";
    }).outPath;
    vscodeExtUniqueId = "vadimcn.vscode-lldb";
    version = "1.9.2";
  };
````

**Comment by deemp** [comment]
It seems to work. Try the `vscodium-with-extensions` from `flake.nix`.
https://github.com/nix-community/nix-vscode-extensions/blob/8cbadbbc055b57ab9b73061a3da7da8beb2315e0/flake.nix#L117

You can contribute versions of that extension for other platforms. See [Extra extensions](https://github.com/nix-community/nix-vscode-extensions#extra-extensions).

**Comment by deemp** [comment]
@cathaysia, I switched to nvfetcher. It will fetch the latest release versions of extensions. See https://github.com/nix-community/nix-vscode-extensions#extra-extensions
