### ISSUE TITLE
template appears to be missing

### ISSUE THREAD

**Issue by buzmeg** [nix-community/nix-vscode-extensions#37]
Running:
```λ nix flake new vscodium-project -t github:nix-community/nix-vscode-extensions```

results in the error:
```
λ nix flake new vscodium-project -t github:nix-community/nix-vscode-extensions
error: flake 'github:nix-community/nix-vscode-extensions' does not provide attribute 'templates.default' or 'defaultTemplate'
```

This template returns a 404:
https://github.com/nix-community/nix-vscode-extensions/blob/master/templates/flake.nix

Thanks.

**Comment by deemp** [comment]
fixed by https://github.com/nix-community/nix-vscode-extensions/commit/f4b6fdc81177d88dddab2e8827fb0912072a1d12
