### ISSUE TITLE
Tweak User Settings

### ISSUE THREAD

**Issue by heywoodlh** [nix-community/nix-vscode-extensions#39]
Is there any way built into the flake to add configuration settings for VSCode? I tried to unsuccessfully find parameters for it.

These are the current config options that I use in my Home Manager VSCode config: https://github.com/heywoodlh/nixos-configs/blob/master/roles/home-manager/desktop.nix#L27-L58

I'd love to be able to use those types of configs with this flake.

I suspect it shouldn't be too difficult to add a config file, but before trying to come up with a solution myself, I thought I would ask, as it seems like something that could be already supported.

(Also, thanks to all involved for such a great flake!)

**Comment by deemp** [comment]
This flake focuses on providing extensions. 

If you meant `settings.json`, I usually generate them for each project.

See 
https://github.com/nix-community/nix-vscode-extensions/blob/0d4b7e78fd260e1665e0b17f8382f7d704385f97/nix-dev/flake.nix#L46

It comes from
https://github.com/deemp/flakes/blob/53d1b8858665e7b259ec57166cdeaa16b03a5e46/codium/flake.nix#L42

**Comment by deemp** [comment]
Not sure if that was a solution to your problem. Feel free to reopen this issue if no
