### ISSUE TITLE
How to get the last version of the extension compatible with the specified vscode version?

### ISSUE THREAD

**Issue by cathaysia** [nix-community/nix-vscode-extensions#41]
I use nix to install vscode. Since flake.lock cannot be updated in such a timely manner, and the vscode version of nix is not always the latest. Expansion incompatibilities often arise. Is it possible to automatically fetch the last extension compatible with a specified vscode version?

UPD: [nix4vscode](https://github.com/cathaysia/nix4vscode) solves this problem.

**Comment by deemp** [comment]
No, we don't provide such functionality.

Every revision (state of the repository at a commit) of `nix-vscode-extensions` contains a set of the latest versions and a set of the release versions of extensions.

Additionally, we provide the [forVSCodeVersion](https://github.com/nix-community/nix-vscode-extensions#extensions) function. You can use an older revision of `nix-vscode-extensions` and check that it provides extensions compatible with your version of VS Code.

**Comment by cathaysia** [comment]
All right. Is it possible to provide similar functionality in future?

**Comment by deemp** [comment]
Yes. Maybe provide via a CLI

**Comment by cathaysia** [comment]
The CLI sounds more like a middle-of-the-road solution. Is it possible to automatically select a suitable version for the specified vscode version? Is this part of the functionality missing because of a limitation caused by nix itself or is it just that there is no plan/motivation to do it at the moment?

**Comment by deemp** [comment]
Selecting a compatible version of an extension requires the following information. 

- All versions of that extension.
- `engine` (compatible VS Code version) of each extension version.

"all versions" will definitely bloat this repo and make fetching it slower.

My assumption is that users update VS Code asap. Then, most extensions with an open upper bound on VS Code version are compatible with the updated VS Code.

**Comment by cathaysia** [comment]
Yes, fetching all versions will undoubtedly result in a very large repository. In this case, I will close this issue first, and please feel free to open it later if you have better ideas

**Comment by MinerSebas** [comment]
As a compromise, you could check what the version of vscode on the current (un-)stable channel, to use as a lower-bound for inclusion.

**Comment by AmeerTaweel** [comment]
Another idea regarding this: For each extension. Store the latest version compatible with a specific VSCode version.

Example: Assume an extension has the following versions:

- Version `u`. Compatible with VSCode version `a`.
- Version `v`. Compatible with VSCode version `a`.
- Version `w`. Compatible with VSCode version `b`.
- Version `x`. Compatible with VSCode version `c`.
- Version `y`. Compatible with VSCode version `c`.
- Version `z`. Compatible with VSCode version `c`.

For such an extension, we only keep versions `v`, `w`, and `z`.

I think this combined with the idea of @MinerSebas can be a viable solution. Defining a reasonable lower-bound limits the number of versions. And we (at most, probably will be much less) store one version per extension per VSCode version from that lower-bound.

**Comment by cathaysia** [comment]
I want to think about it from another angle.

 Is it possible to calculate the minimum required version of vscode in the current commit. Then tag this commit by vscode's version. If tag is existed, just update it to the lastest commit.

This will cause many extensions to be unable to use the latest version, but avoids breaking changes. The only concern is whether this function will be completely ineffective due to outdated extensions.

**Comment by AmeerTaweel** [comment]
@cathaysia Correct me if I'm wrong. But (I assume that) some older extensions will not be compatible with newer versions of VSCode. In that case, even if you have a version of VSCode more recent than the "minimum required", you might get incompatible extensions.

**Comment by cathaysia** [comment]
Yes, but if we specify the upper and lower bounds of the vscode version at the same time, the chances of conflict between the two boundaries will be high. So we can only assume that the low version extension is compatible with the high version vscode. In other words, the upgrade of vscode will not break compatibility.

What we need may not be a tag that works perfectly, but a tag that works in most cases. This stems from a compromise on warehouse size.

In fact, it might be better to be able to query the extended compatible version at "runtime". But it will introduce impure

**Comment by deemp** [comment]
I'm in favor of @AmeerTaweel 's idea (https://github.com/nix-community/nix-vscode-extensions/issues/41#issuecomment-1687764105).

Currently, we fetch latest and release extensions separately. Responses

**Comment by AmeerTaweel** [comment]
By the way, is there any chance [this](https://github.com/NixOS/nixpkgs/issues/208456) will be approved.

**Comment by AmeerTaweel** [comment]
By the way, do you think [this](https://github.com/NixOS/nixpkgs/issues/208456) will be approved? Because if that is the case, we can keep only the extension versions compatible with whatever version of VSCode is in `nixpkgs`. That way we only have one version per extension, and we always have compatible versions. However, this depends on being able to merge with `nixpkgs`.

**Comment by arjan-s** [comment]
Sorry for this "me too" like answer, but I'm running into this issue too. Currently `vscode` is at version 1.81.1, while the latest pre-release `ms-python.python` requires 1.82.0 or higher. This cannot be solved currently, because:
- vscode 1.82.0 is not yet available in nixpkgs
- `ms-python.python` is not available in the `extensions.x86_64-linux.vscode-marketplace-release` set
- `ms-python.python` is not available in the `(extensions.x86_64-linux.forVSCodeVersion "1.81.1").vscode-marketplace` set

Can you think of a way to get this to work?

**Comment by deemp** [comment]
Sorry for silence. Started a new semester. 

@AmeerTaweel 

> we can keep only the extension versions compatible with whatever version of VSCode is in nixpkgs

This option still implies that we process large responses. To see large responses, run [haskell/requests.sh](https://github.com/nix-community/nix-vscode-extensions/blob/cbdf894ac986b9696742efd76b5f199e24db3115/haskell/requests.sh)

@arjan-s

> Can you think of a way to get this to work?

If the latest release version of `ms-python.python` is compatible with vscode 1.81.1, you can add `ms-python.python` to the config ([README](https://github.com/nix-community/nix-vscode-extensions#release-extensions)). Then, the release version of `ms-python.python` will be fetched.

**Comment by deemp** [comment]
@arjan-s

> Can you think of a way to get this to work?

If the latest release version of `ms-python.python` is compatible with vscode 1.81.1, you can add `ms-python.python` to the config ([README](https://github.com/nix-community/nix-vscode-extensions#release-extensions)). Then, the release version of `ms-python.python` will be fetched.

**Comment by yangm97** [comment]
@deemp but only a set of very specific extensions are available on the `-release` closure =/

**Comment by AmeerTaweel** [comment]
@yangm97 I think that @deemp meant that you fork the repo and add the extension you want until we figure something out.

**Comment by AmeerTaweel** [comment]
> To see large responses, run [haskell/requests.sh](https://github.com/nix-community/nix-vscode-extensions/blob/cbdf894ac986b9696742efd76b5f199e24db3115/haskell/requests.sh)

@deemp I will run it and see...

**Comment by AmeerTaweel** [comment]
@deemp maybe a better work to describe the response was "huge" lol.

![image](https://github.com/nix-community/nix-vscode-extensions/assets/20538273/bc6cbd9e-ff8a-40d0-8ef9-455f81a4acf1)

**Comment by AmeerTaweel** [comment]
I found an open [issue](https://github.com/microsoft/vsmarketplace/issues/106) about this.

**Comment by cathaysia** [comment]
I'm currently working on a node.nix-like software. It reads the vscode version and extension list from toml and then generates nix expressions. If all goes well, it should be open in the next week or so. If this tool is written, nix-extensions may no longer be needed to make changes.

**Comment by deemp** [comment]
@cathaysia, cool idea!

**Comment by cathaysia** [comment]
I've just removed the hardcoded data from the code and implemented a very basic prototype (so haven't even added a README yet), but it should be enough to illustrate some of my thinking. I left a config.toml in the repository, just run cargo run -- -f config.toml to see the generated nix expressions printed to the console.

https://github.com/cathaysia/nix4vscode

**Comment by yangm97** [comment]
> @deemp maybe a better work to describe the response was "huge" lol.
> 
> ![image](https://user-images.githubusercontent.com/20538273/266138832-bc6cbd9e-ff8a-40d0-8ef9-455f81a4acf1.png)
> 
> The GitHub action takes around 20 minutes to finish. The proposed idea will make it 20 hours. We should find a way to tell the API to send shorter responses.

Sorry if I'm being captain obvious but does the API provide any sort of caching header? Like. etag or last-modified? Wouldn't it be possible to cache these and make use of HEAD requests before attempting a full GET?

**Comment by deemp** [comment]
IDK. How would you use it?

**Comment by yangm97** [comment]
So the idea would be to store the cache header for each request somewhere (ideally the CI cache but could be on the repo if it makes implementation easier, those headers are short anyway). The first run would probably take a long time but as extensions don't get frequently updated all at once, subsequent runs would be much faster as the HEAD requests could be parallelized without straining the API.

**Comment by cathaysia** [comment]
I just updated the [nix4vscode](https://github.com/cathaysia/nix4vscode)'s README. Anyone interested?

**Comment by deemp** [comment]
I added a link to nix4vscode to your first message in this issue. Anyone interested can continue discussing it in your repo.

**Comment by cathaysia** [comment]
thanks😃
________________________________

**Comment by deemp** [comment]
I will close this issue since the solution is implemented in the [nix4vscode](https://github.com/cathaysia/nix4vscode) repo.
