### ISSUE TITLE
What is `__filter` in flake.nix?

### ISSUE THREAD

**Issue by Septias** [nix-community/nix-vscode-extensions#50]
The top-level `flake.nix` uses a lot of dunder methods like `__filter` which look like the library functions, but aren't. I also don't find any definition for them in the file so I wonder how the whole flake even works. Can someone explain this shortly?

**Comment by deemp** [comment]
@Septias, I believe you've discovered them in `nix repl`. Try running repl inside this repository without `:lf`. You'll see these functions. They're builtins.
