### ISSUE TITLE
Improve overrides.nix

### ISSUE THREAD

**Issue by deemp** [nix-community/nix-vscode-extensions#55]
- [x] According to https://github.com/nix-community/nix-vscode-extensions/issues/31#issuecomment-1951128781, we may not need to set `sourceRoot = "extension"` when https://github.com/NixOS/nixpkgs/pull/289721 is merged.
- [ ] Adopt workarounds from `nixpkgs`
  - https://github.com/NixOS/nixpkgs/issues/270423#issuecomment-1902482401
- [x] Simplify and publish `overrides.nix` to a separate branch without all cache files so that other solutions like [nix4vscode](https://github.com/nix-community/nix4vscode) can make use of overrides.

**Comment by FraGag** [comment]
https://github.com/NixOS/nixpkgs/pull/289721 was just merged into master. Once it gets merged into nixpkgs-unstable and nixos-unstable, then we'll be able to remove `sourceRoot = "extension"` in `overrides.nix`.

I advise waiting at least until it's in nixos-unstable, in case someone uses nix-vscode-extensions in a flake that changes its nixpkgs input to follow the nixos-unstable branch. If we want to be extra cautious, we could also wait for https://github.com/NixOS/nixpkgs/pull/303445, which backports the change to the release-23.11 branch.

**Comment by deemp** [comment]
Should be resolved in #62
