### ISSUE TITLE
Extension packs doesn't work

### ISSUE THREAD

**Issue by musjj** [nix-community/nix-vscode-extensions#67]
It seems that extension packs doesn't work. For example: https://marketplace.visualstudio.com/items?itemName=vshaxe.haxe-extension-pack

It only installs the pack but nothing else.

**Comment by deemp** [comment]
You should list extensions from a pack one by one. I explained this in the Note ([link](https://github.com/nix-community/nix-vscode-extensions#note), [commit](https://github.com/nix-community/nix-vscode-extensions/commit/712b25bf2488e717b47b98a8f9d9561e23b840d3)).

**Comment by deemp** [comment]
@musjj, feel free to ask new questions in new issues.
