### ISSUE TITLE
Where are the extensions?

### ISSUE THREAD

**Issue by yajo** [nix-community/nix-vscode-extensions#68]
The README talks about 40000 extensions.

I can only find 7:

```
nix-repl> :lf github:nix-community/nix-vscode-extensions/27ce569
nix-repl> extensions.x86_64-linux.vscode-marketplace-release.<TAB>
extensions.x86_64-linux.vscode-marketplace-release.eamodio
extensions.x86_64-linux.vscode-marketplace-release.github
extensions.x86_64-linux.vscode-marketplace-release.ms-dotnettools
extensions.x86_64-linux.vscode-marketplace-release.ms-vscode-remote
extensions.x86_64-linux.vscode-marketplace-release.rust-lang
extensions.x86_64-linux.vscode-marketplace-release.stkb
extensions.x86_64-linux.vscode-marketplace-release.vadimcn
```

Where are the other 39.993? 🤔

**Comment by deemp** [comment]
Have you checked `extensions.x86_64-linux.vscode-marketplace.<TAB>`?

**Comment by yajo** [comment]
There they are! Thanks!

**Comment by kqvanity** [comment]
@deemp Why are the release extensions are so scarce compared to the default pre-release?(Jupyter Notebook is incompatible with unstable vscode for me)

**Comment by deemp** [comment]
@kqvanity, because it may be very slow to fetch the release versions. See https://github.com/nix-community/nix-vscode-extensions/issues/41#issuecomment-1689259238. Check [nix](https://github.com/nix-community/nix4vscode) if you need extensions compatible with your VS Code version.
