### ISSUE TITLE
Change nixos.wiki links to wiki.nixos.org in README

### ISSUE THREAD

**Issue by artur-sannikov** [nix-community/nix-vscode-extensions#77]
AFAIK www.nixos.wiki is dead and we should use www.wiki.nixos.org. See FAQ on the official [wiki](https://wiki.nixos.org/wiki/FAQ#Why_is_there_a_new_wiki?_What_is_with_nixos.wiki).

I can open a PR.

**Comment by deemp** [comment]
@artur-sannikov, would be nice if you open a PR.
