### ISSUE TITLE
CI failing since a week ago

### ISSUE THREAD

**Issue by musjj** [nix-community/nix-vscode-extensions#81]
I wanted to get an update to an extension from yesterday, but it looks like that this repo stopped updating since a week ago: 018196c371073d669510fd69dd2f6dc0ec608c41. Did something happen to the CI?

EDIT: Oh yeah, the CI is failing: https://github.com/nix-community/nix-vscode-extensions/actions/runs/11319588054/job/31475864418

```
error: unable to download 'https://github.com/vadimcn/codelldb/releases/download/v1.11.0/codelldb-x86_64-darwin.vsix': HTTP error 404

       response body:

       Not Found
```

It looks like `codelldb` changed the asset names: https://github.com/vadimcn/codelldb/releases

**Comment by deemp** [comment]
Closed by #82
